jobs:
  tests:
    services:
      db:
        image: postgres:16.2
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: rom_repository
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
        include:
          - ruby: "3.3"
            coverage: "true"
            use_transproc_master: "true"
            use_use_rom_sql_master: "true"
    env:
      COVERAGE: ${{matrix.coverage}}
      BASE_DB_URI: localhost/rom_repository
      USE_TRANSPROC_MASTER: ${{matrix.use_dry_transformer_master}}
      USE_ROM_SQL_MASTER: ${{matrix.use_rom_sql_master}}
      CODACY_RUN_LOCAL: ${{matrix.coverage}}
      CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
      APT_DEPS: "libpq-dev libsqlite3-dev"
